export const classes = [
  {
    id: "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
    name: "CS 4152 Senior SWE II",
    email: "williamsmith@example.com",
    subject: "Computer Science",
    text: "This course is a completion of a two-quarter software development experience. Student teams will implement, test and deploy systems they began in CSC 4151. Class time will be primarily devoted to the application of software engineering principles to their project, technical reviews, and formal presentation of the completed system.",
    date: "2023-10-22T09:00:00",
    completed: true,
    isRemaining: false,
    labels: ["meeting", "work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 4898 Senior Capstone",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "This senior capstone course will complete and deliver the software product started in CSC 4151 & CSC 4152, and explore topics and frontiers in computer science and information systems. Students will review and summarize their educational experience at SPU in a written essay. Preparation for a career and lifelong learning options are included. Students will investigate and write a term paper on one or more current topics within the computing industry. This course is the completion of a three-quarter team software product development sequence.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: false,
    labels: ["work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 3430 - Algorithm Design and Analysis",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "Studies algorithmic, problem solving approaches such as greedy, divide and conquer, and dynamic programming. Covers the design and analysis of algorithms for searching, sorting, string processing, table management, and graphs. Includes principles of computational complexity and analysis.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: true,
    labels: ["work", "important"],
  },
  {
    id: "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
    name: "CS 4152 Senior SWE II",
    email: "williamsmith@example.com",
    subject: "Computer Science",
    text: "This course is a completion of a two-quarter software development experience. Student teams will implement, test and deploy systems they began in CSC 4151. Class time will be primarily devoted to the application of software engineering principles to their project, technical reviews, and formal presentation of the completed system.",
    date: "2023-10-22T09:00:00",
    completed: true,
    isRemaining: false,
    labels: ["meeting", "work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 4898 Senior Capstone",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "This senior capstone course will complete and deliver the software product started in CSC 4151 & CSC 4152, and explore topics and frontiers in computer science and information systems. Students will review and summarize their educational experience at SPU in a written essay. Preparation for a career and lifelong learning options are included. Students will investigate and write a term paper on one or more current topics within the computing industry. This course is the completion of a three-quarter team software product development sequence.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: false,
    labels: ["work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 3430 - Algorithm Design and Analysis",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "Studies algorithmic, problem solving approaches such as greedy, divide and conquer, and dynamic programming. Covers the design and analysis of algorithms for searching, sorting, string processing, table management, and graphs. Includes principles of computational complexity and analysis.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: true,
    labels: ["work", "important"],
  },
  {
    id: "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
    name: "CS 4152 Senior SWE II",
    email: "williamsmith@example.com",
    subject: "Computer Science",
    text: "This course is a completion of a two-quarter software development experience. Student teams will implement, test and deploy systems they began in CSC 4151. Class time will be primarily devoted to the application of software engineering principles to their project, technical reviews, and formal presentation of the completed system.",
    date: "2023-10-22T09:00:00",
    completed: true,
    isRemaining: false,
    labels: ["meeting", "work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 4898 Senior Capstone",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "This senior capstone course will complete and deliver the software product started in CSC 4151 & CSC 4152, and explore topics and frontiers in computer science and information systems. Students will review and summarize their educational experience at SPU in a written essay. Preparation for a career and lifelong learning options are included. Students will investigate and write a term paper on one or more current topics within the computing industry. This course is the completion of a three-quarter team software product development sequence.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: false,
    labels: ["work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 3430 - Algorithm Design and Analysis",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "Studies algorithmic, problem solving approaches such as greedy, divide and conquer, and dynamic programming. Covers the design and analysis of algorithms for searching, sorting, string processing, table management, and graphs. Includes principles of computational complexity and analysis.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: true,
    labels: ["work", "important"],
  },
  {
    id: "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
    name: "CS 4152 Senior SWE II",
    email: "williamsmith@example.com",
    subject: "Computer Science",
    text: "This course is a completion of a two-quarter software development experience. Student teams will implement, test and deploy systems they began in CSC 4151. Class time will be primarily devoted to the application of software engineering principles to their project, technical reviews, and formal presentation of the completed system.",
    date: "2023-10-22T09:00:00",
    completed: true,
    isRemaining: false,
    labels: ["meeting", "work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 4898 Senior Capstone",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "This senior capstone course will complete and deliver the software product started in CSC 4151 & CSC 4152, and explore topics and frontiers in computer science and information systems. Students will review and summarize their educational experience at SPU in a written essay. Preparation for a career and lifelong learning options are included. Students will investigate and write a term paper on one or more current topics within the computing industry. This course is the completion of a three-quarter team software product development sequence.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: false,
    labels: ["work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 3430 - Algorithm Design and Analysis",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "Studies algorithmic, problem solving approaches such as greedy, divide and conquer, and dynamic programming. Covers the design and analysis of algorithms for searching, sorting, string processing, table management, and graphs. Includes principles of computational complexity and analysis.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: true,
    labels: ["work", "important"],
  },
  {
    id: "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
    name: "CS 4152 Senior SWE II",
    email: "williamsmith@example.com",
    subject: "Computer Science",
    text: "This course is a completion of a two-quarter software development experience. Student teams will implement, test and deploy systems they began in CSC 4151. Class time will be primarily devoted to the application of software engineering principles to their project, technical reviews, and formal presentation of the completed system.",
    date: "2023-10-22T09:00:00",
    completed: true,
    isRemaining: false,
    labels: ["meeting", "work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 4898 Senior Capstone",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "This senior capstone course will complete and deliver the software product started in CSC 4151 & CSC 4152, and explore topics and frontiers in computer science and information systems. Students will review and summarize their educational experience at SPU in a written essay. Preparation for a career and lifelong learning options are included. Students will investigate and write a term paper on one or more current topics within the computing industry. This course is the completion of a three-quarter team software product development sequence.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: false,
    labels: ["work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 3430 - Algorithm Design and Analysis",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "Studies algorithmic, problem solving approaches such as greedy, divide and conquer, and dynamic programming. Covers the design and analysis of algorithms for searching, sorting, string processing, table management, and graphs. Includes principles of computational complexity and analysis.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: true,
    labels: ["work", "important"],
  },
  {
    id: "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
    name: "CS 4152 Senior SWE II",
    email: "williamsmith@example.com",
    subject: "Computer Science",
    text: "This course is a completion of a two-quarter software development experience. Student teams will implement, test and deploy systems they began in CSC 4151. Class time will be primarily devoted to the application of software engineering principles to their project, technical reviews, and formal presentation of the completed system.",
    date: "2023-10-22T09:00:00",
    completed: true,
    isRemaining: false,
    labels: ["meeting", "work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 4898 Senior Capstone",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "This senior capstone course will complete and deliver the software product started in CSC 4151 & CSC 4152, and explore topics and frontiers in computer science and information systems. Students will review and summarize their educational experience at SPU in a written essay. Preparation for a career and lifelong learning options are included. Students will investigate and write a term paper on one or more current topics within the computing industry. This course is the completion of a three-quarter team software product development sequence.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: false,
    labels: ["work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 3430 - Algorithm Design and Analysis",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "Studies algorithmic, problem solving approaches such as greedy, divide and conquer, and dynamic programming. Covers the design and analysis of algorithms for searching, sorting, string processing, table management, and graphs. Includes principles of computational complexity and analysis.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: true,
    labels: ["work", "important"],
  },
  {
    id: "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
    name: "CS 4152 Senior SWE II",
    email: "williamsmith@example.com",
    subject: "Computer Science",
    text: "This course is a completion of a two-quarter software development experience. Student teams will implement, test and deploy systems they began in CSC 4151. Class time will be primarily devoted to the application of software engineering principles to their project, technical reviews, and formal presentation of the completed system.",
    date: "2023-10-22T09:00:00",
    completed: true,
    isRemaining: false,
    labels: ["meeting", "work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 4898 Senior Capstone",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "This senior capstone course will complete and deliver the software product started in CSC 4151 & CSC 4152, and explore topics and frontiers in computer science and information systems. Students will review and summarize their educational experience at SPU in a written essay. Preparation for a career and lifelong learning options are included. Students will investigate and write a term paper on one or more current topics within the computing industry. This course is the completion of a three-quarter team software product development sequence.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: false,
    labels: ["work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 3430 - Algorithm Design and Analysis",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "Studies algorithmic, problem solving approaches such as greedy, divide and conquer, and dynamic programming. Covers the design and analysis of algorithms for searching, sorting, string processing, table management, and graphs. Includes principles of computational complexity and analysis.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: true,
    labels: ["work", "important"],
  },
  {
    id: "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
    name: "CS 4152 Senior SWE II",
    email: "williamsmith@example.com",
    subject: "Computer Science",
    text: "This course is a completion of a two-quarter software development experience. Student teams will implement, test and deploy systems they began in CSC 4151. Class time will be primarily devoted to the application of software engineering principles to their project, technical reviews, and formal presentation of the completed system.",
    date: "2023-10-22T09:00:00",
    completed: true,
    isRemaining: false,
    labels: ["meeting", "work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 4898 Senior Capstone",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "This senior capstone course will complete and deliver the software product started in CSC 4151 & CSC 4152, and explore topics and frontiers in computer science and information systems. Students will review and summarize their educational experience at SPU in a written essay. Preparation for a career and lifelong learning options are included. Students will investigate and write a term paper on one or more current topics within the computing industry. This course is the completion of a three-quarter team software product development sequence.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: false,
    labels: ["work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 3430 - Algorithm Design and Analysis",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "Studies algorithmic, problem solving approaches such as greedy, divide and conquer, and dynamic programming. Covers the design and analysis of algorithms for searching, sorting, string processing, table management, and graphs. Includes principles of computational complexity and analysis.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: true,
    labels: ["work", "important"],
  },
  {
    id: "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
    name: "CS 4152 Senior SWE II",
    email: "williamsmith@example.com",
    subject: "Computer Science",
    text: "This course is a completion of a two-quarter software development experience. Student teams will implement, test and deploy systems they began in CSC 4151. Class time will be primarily devoted to the application of software engineering principles to their project, technical reviews, and formal presentation of the completed system.",
    date: "2023-10-22T09:00:00",
    completed: true,
    isRemaining: false,
    labels: ["meeting", "work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 4898 Senior Capstone",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "This senior capstone course will complete and deliver the software product started in CSC 4151 & CSC 4152, and explore topics and frontiers in computer science and information systems. Students will review and summarize their educational experience at SPU in a written essay. Preparation for a career and lifelong learning options are included. Students will investigate and write a term paper on one or more current topics within the computing industry. This course is the completion of a three-quarter team software product development sequence.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: false,
    labels: ["work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 3430 - Algorithm Design and Analysis",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "Studies algorithmic, problem solving approaches such as greedy, divide and conquer, and dynamic programming. Covers the design and analysis of algorithms for searching, sorting, string processing, table management, and graphs. Includes principles of computational complexity and analysis.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: true,
    labels: ["work", "important"],
  },
  {
    id: "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
    name: "CS 4152 Senior SWE II",
    email: "williamsmith@example.com",
    subject: "Computer Science",
    text: "This course is a completion of a two-quarter software development experience. Student teams will implement, test and deploy systems they began in CSC 4151. Class time will be primarily devoted to the application of software engineering principles to their project, technical reviews, and formal presentation of the completed system.",
    date: "2023-10-22T09:00:00",
    completed: true,
    isRemaining: false,
    labels: ["meeting", "work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 4898 Senior Capstone",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "This senior capstone course will complete and deliver the software product started in CSC 4151 & CSC 4152, and explore topics and frontiers in computer science and information systems. Students will review and summarize their educational experience at SPU in a written essay. Preparation for a career and lifelong learning options are included. Students will investigate and write a term paper on one or more current topics within the computing industry. This course is the completion of a three-quarter team software product development sequence.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: false,
    labels: ["work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 3430 - Algorithm Design and Analysis",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "Studies algorithmic, problem solving approaches such as greedy, divide and conquer, and dynamic programming. Covers the design and analysis of algorithms for searching, sorting, string processing, table management, and graphs. Includes principles of computational complexity and analysis.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: true,
    labels: ["work", "important"],
  },
  {
    id: "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
    name: "CS 4152 Senior SWE II",
    email: "williamsmith@example.com",
    subject: "Computer Science",
    text: "This course is a completion of a two-quarter software development experience. Student teams will implement, test and deploy systems they began in CSC 4151. Class time will be primarily devoted to the application of software engineering principles to their project, technical reviews, and formal presentation of the completed system.",
    date: "2023-10-22T09:00:00",
    completed: true,
    isRemaining: false,
    labels: ["meeting", "work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 4898 Senior Capstone",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "This senior capstone course will complete and deliver the software product started in CSC 4151 & CSC 4152, and explore topics and frontiers in computer science and information systems. Students will review and summarize their educational experience at SPU in a written essay. Preparation for a career and lifelong learning options are included. Students will investigate and write a term paper on one or more current topics within the computing industry. This course is the completion of a three-quarter team software product development sequence.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: false,
    labels: ["work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 3430 - Algorithm Design and Analysis",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "Studies algorithmic, problem solving approaches such as greedy, divide and conquer, and dynamic programming. Covers the design and analysis of algorithms for searching, sorting, string processing, table management, and graphs. Includes principles of computational complexity and analysis.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: true,
    labels: ["work", "important"],
  },
  {
    id: "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
    name: "CS 4152 Senior SWE II",
    email: "williamsmith@example.com",
    subject: "Computer Science",
    text: "This course is a completion of a two-quarter software development experience. Student teams will implement, test and deploy systems they began in CSC 4151. Class time will be primarily devoted to the application of software engineering principles to their project, technical reviews, and formal presentation of the completed system.",
    date: "2023-10-22T09:00:00",
    completed: true,
    isRemaining: false,
    labels: ["meeting", "work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 4898 Senior Capstone",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "This senior capstone course will complete and deliver the software product started in CSC 4151 & CSC 4152, and explore topics and frontiers in computer science and information systems. Students will review and summarize their educational experience at SPU in a written essay. Preparation for a career and lifelong learning options are included. Students will investigate and write a term paper on one or more current topics within the computing industry. This course is the completion of a three-quarter team software product development sequence.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: false,
    labels: ["work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 3430 - Algorithm Design and Analysis",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "Studies algorithmic, problem solving approaches such as greedy, divide and conquer, and dynamic programming. Covers the design and analysis of algorithms for searching, sorting, string processing, table management, and graphs. Includes principles of computational complexity and analysis.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: true,
    labels: ["work", "important"],
  },
  {
    id: "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
    name: "CS 4152 Senior SWE II",
    email: "williamsmith@example.com",
    subject: "Computer Science",
    text: "This course is a completion of a two-quarter software development experience. Student teams will implement, test and deploy systems they began in CSC 4151. Class time will be primarily devoted to the application of software engineering principles to their project, technical reviews, and formal presentation of the completed system.",
    date: "2023-10-22T09:00:00",
    completed: true,
    isRemaining: false,
    labels: ["meeting", "work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 4898 Senior Capstone",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "This senior capstone course will complete and deliver the software product started in CSC 4151 & CSC 4152, and explore topics and frontiers in computer science and information systems. Students will review and summarize their educational experience at SPU in a written essay. Preparation for a career and lifelong learning options are included. Students will investigate and write a term paper on one or more current topics within the computing industry. This course is the completion of a three-quarter team software product development sequence.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: false,
    labels: ["work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 3430 - Algorithm Design and Analysis",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "Studies algorithmic, problem solving approaches such as greedy, divide and conquer, and dynamic programming. Covers the design and analysis of algorithms for searching, sorting, string processing, table management, and graphs. Includes principles of computational complexity and analysis.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: true,
    labels: ["work", "important"],
  },
  {
    id: "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
    name: "CS 4152 Senior SWE II",
    email: "williamsmith@example.com",
    subject: "Computer Science",
    text: "This course is a completion of a two-quarter software development experience. Student teams will implement, test and deploy systems they began in CSC 4151. Class time will be primarily devoted to the application of software engineering principles to their project, technical reviews, and formal presentation of the completed system.",
    date: "2023-10-22T09:00:00",
    completed: true,
    isRemaining: false,
    labels: ["meeting", "work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 4898 Senior Capstone",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "This senior capstone course will complete and deliver the software product started in CSC 4151 & CSC 4152, and explore topics and frontiers in computer science and information systems. Students will review and summarize their educational experience at SPU in a written essay. Preparation for a career and lifelong learning options are included. Students will investigate and write a term paper on one or more current topics within the computing industry. This course is the completion of a three-quarter team software product development sequence.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: false,
    labels: ["work", "important"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "CSC 3430 - Algorithm Design and Analysis",
    email: "alicesmith@example.com",
    subject: "Computer Science",
    text: "Studies algorithmic, problem solving approaches such as greedy, divide and conquer, and dynamic programming. Covers the design and analysis of algorithms for searching, sorting, string processing, table management, and graphs. Includes principles of computational complexity and analysis.",
    date: "2023-10-22T10:30:00",
    completed: false,
    isRemaining: true,
    labels: ["work", "important"],
  },
];

export type Class = (typeof classes)[number];
