import { Schedule } from "@/stores/VisualizeStore";

// This temporary data will be gone once we have the plans store
export const mockSchedules: Schedule[] = [
  {
    id: "1",
    name: "Computer Science BS With Mathemathics Minor",
    quarters: [
      {
        id: 1,
        name: "Fall 2021",
        courses: [
          {
            code: "CSE 110",
            title: "Software Engineering",
            status: "completed",
            credits: 4,
            prerequisites: [],
            p_id: 1,
            order_id: 1,
          },
          {
            code: "CSE 120",
            title: "Database Systems",
            status: "completed",
            credits: 4,
            prerequisites: [],
            p_id: 1,
            order_id: 2,
          },
          {
            code: "UCOR 1100",
            title: "Database Systems",
            status: "completed",
            credits: 4,
            prerequisites: [],
            p_id: 1,
            order_id: 3,
          },
        ],
        totalCredits: 8,
      },
      {
        id: 2,
        name: "Winter 2022",
        courses: [
          {
            code: "CSE 130",
            title: "Operating Systems",
            credits: 4,
            status: "in progress",
            prerequisites: [
              {
                code: "CSE 110",
                title: "Software Engineering",
                credits: 4,
                prerequisites: [],
              },
            ],
            p_id: 2,
            order_id: 1,
          },
          {
            code: "CSE 140",
            title: "Computer Networks",
            status: "in progress",
            credits: 4,
            prerequisites: [],
            p_id: 2,
            order_id: 2,
          },
          {
            code: "UCOR 2000",
            title: "University Core",
            credits: 4,
            status: "in progress",
            prerequisites: [
              {
                code: "UCOR 1100",
                title: "University Core",
                credits: 4,
                prerequisites: [],
              },
            ],
            p_id: 2,
            order_id: 3,
          },
        ],
        totalCredits: 8,
      },
      {
        id: 3,
        name: "Spring 2022",
        courses: [
          {
            code: "CSE 147",
            title: "Computer Architecture",
            credits: 4,
            status: "registered",
            prerequisites: [
              {
                code: "CSE 110",
                title: "Software Engineering",
                credits: 4,
                prerequisites: [],
              },
              {
                code: "CSE 140",
                title: "Computer Networks",
                credits: 4,
                prerequisites: [],
              },
            ],
            p_id: 3,
            order_id: 1,
          },
          {
            code: "CSE 153",
            title: "Machine Learning",
            status: "registered",
            credits: 4,
            prerequisites: [],
            p_id: 3,
            order_id: 2,
          },
          {
            code: "UCOR 3100",
            title: "Christian Faith and University Core",
            credits: 4,
            status: "registered",
            prerequisites: [
              {
                code: "UCOR 1100",
                title: "University Core",
                credits: 4,
                prerequisites: [],
              },
            ],
            p_id: 3,
            order_id: 3,
          },
        ],
        totalCredits: 8,
      },
    ],
    totalCredits: 24,
    dateCreated: new Date(),
    fields: ["Computer Science", "Mathematics"],
  },
  {
    id: "2",
    name: "Sample Schedule 2",
    quarters: [
      {
        id: 1,
        name: "Fall 2021",
        courses: [
          {
            code: "CSE 110",
            title: "Software Engineering",
            credits: 4,
            status: "in progress",
            prerequisites: [],
            p_id: 1,
            order_id: 1,
          },
          {
            code: "CSE 120",
            title: "Database Systems",
            credits: 4,
            status: "in progress",
            prerequisites: [],
            p_id: 1,
            order_id: 2,
          },
        ],
        totalCredits: 8,
      },
      {
        id: 2,
        name: "Winter 2022",
        courses: [
          {
            code: "CSE 130",
            title: "Operating Systems",
            credits: 4,
            prerequisites: [],
            p_id: 2,
            order_id: 1,
          },
          {
            code: "CSE 140",
            title: "Computer Networks",
            credits: 4,
            prerequisites: [],
            p_id: 2,
            order_id: 2,
          },
        ],
        totalCredits: 8,
      },
    ],
    totalCredits: 16,
    dateCreated: new Date(),
    fields: ["Computer Science"],
  },
  {
    id: "3",
    name: "Sample Schedule 2",
    quarters: [
      {
        id: 1,
        name: "Fall 2021",
        courses: [
          {
            code: "CSE 110",
            title: "Software Engineering",
            credits: 4,
            status: "in progress",
            prerequisites: [],
            p_id: 1,
            order_id: 1,
          },
          {
            code: "CSE 120",
            title: "Database Systems",
            credits: 4,
            status: "in progress",
            prerequisites: [],
            p_id: 1,
            order_id: 2,
          },
        ],
        totalCredits: 8,
      },
      {
        id: 2,
        name: "Winter 2022",
        courses: [
          {
            code: "CSE 130",
            title: "Operating Systems",
            credits: 4,
            prerequisites: [],
            p_id: 2,
            order_id: 1,
          },
          {
            code: "CSE 140",
            title: "Computer Networks",
            credits: 4,
            prerequisites: [],
            p_id: 2,
            order_id: 2,
          },
        ],
        totalCredits: 8,
      },
    ],
    totalCredits: 16,
    dateCreated: new Date(),
    fields: ["Computer Science"],
  },
  {
    id: "4",
    name: "Sample Schedule 2",
    quarters: [
      {
        id: 1,
        name: "Fall 2021",
        courses: [
          {
            code: "CSE 110",
            title: "Software Engineering",
            credits: 4,
            status: "in progress",
            prerequisites: [],
            p_id: 1,
            order_id: 1,
          },
          {
            code: "CSE 120",
            title: "Database Systems",
            credits: 4,
            status: "in progress",
            prerequisites: [],
            p_id: 1,
            order_id: 2,
          },
        ],
        totalCredits: 8,
      },
      {
        id: 2,
        name: "Winter 2022",
        courses: [
          {
            code: "CSE 130",
            title: "Operating Systems",
            credits: 4,
            prerequisites: [],
            p_id: 2,
            order_id: 1,
          },
          {
            code: "CSE 140",
            title: "Computer Networks",
            credits: 4,
            prerequisites: [],
            p_id: 2,
            order_id: 2,
          },
        ],
        totalCredits: 8,
      },
    ],
    totalCredits: 16,
    dateCreated: new Date(),
    fields: ["Computer Science"],
  },
  {
    id: "5",
    name: "Sample Schedule 2",
    quarters: [
      {
        id: 1,
        name: "Fall 2021",
        courses: [
          {
            code: "CSE 110",
            title: "Software Engineering",
            credits: 4,
            status: "in progress",
            prerequisites: [],
            p_id: 1,
            order_id: 1,
          },
          {
            code: "CSE 120",
            title: "Database Systems",
            credits: 4,
            status: "in progress",
            prerequisites: [],
            p_id: 1,
            order_id: 2,
          },
        ],
        totalCredits: 8,
      },
      {
        id: 2,
        name: "Winter 2022",
        courses: [
          {
            code: "CSE 130",
            title: "Operating Systems",
            credits: 4,
            prerequisites: [],
            p_id: 2,
            order_id: 1,
          },
          {
            code: "CSE 140",
            title: "Computer Networks",
            credits: 4,
            prerequisites: [],
            p_id: 2,
            order_id: 2,
          },
        ],
        totalCredits: 8,
      },
    ],
    totalCredits: 16,
    dateCreated: new Date(),
    fields: ["Computer Science"],
  },
];
