export { default as SeattleLanding } from "./LandingPage/Seattle-Landing.jpg";
export { default as FeatureOne } from "./LandingPage/Feature1.jpg";
export { default as FeatureTwo } from "./LandingPage/Feature2.jpg";
export { default as FeatureThree } from "./LandingPage/Feature3.jpg";
export { default as GPAHero } from "./LandingPage/GPAHeroPhoto.jpg";
export { default as Laptop } from "./LandingPage/laptop.jpg";
export { default as DontStress } from "./LandingPage/dontstress.jpg";
export { default as VisionOne } from "./LandingPage/VisionPhoto1.jpg";
export { default as VisionTwo } from "./LandingPage/VisionPhoto2.jpg";
export { default as HowardSZ } from "./advisors/1.jpg";
export { default as KrienenHM } from "./advisors/2.jpg";
export { default as MorrisCG } from "./advisors/3.jpg";
export { default as RendahlAB } from "./advisors/4.jpg";
export { default as VogelMS } from "./advisors/5.jpg";
export { default as BannerGIF } from "./banner/banner.gif"
